version: '3'

services:
  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8082:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d.d
    networks:
      - backend

  app:
    container_name: "app"
    image: app

    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - images_data:/app/static/images
    networks:
      - backend

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
      PGLOG: /var/lib/postgresql/data/logs/pglog
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./log:/var/lib/postgresql/data/logs
    command: postgres -c log_destination=stderr -c logging_collector=on
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
  images_data:
